# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

main:

  # About tab
  - name: About
    pageRef: about
    weight: 10
  - name: Team
    pageRef: team
    weight: 20

footer:
  - name: GitHub
    url: https://github.com/Illinois-ATLAS
    pre: github
    weight: 100